version: "3.9"
services:
  firestore-emulator:
    image: "gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators"
    ports:
      - "8087:8087"
    command: ["gcloud", "emulators", "firestore", "start", "--host-port=0.0.0.0:8087"]
